##
# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: test  # Запускать только после успешного выполнения тестов

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add self-signed certificate
        run: |
          sudo mkdir -p /usr/local/share/ca-certificates
          sudo cp  ./.docker/158.160.12.251.crt /usr/local/share/ca-certificates/
          sudo update-ca-certificates



      - name: Build and push Docker image
        run: |
          docker build -t 158.160.12.251:443/flask-ci-cd-demo:latest .
          docker push 158.160.12.251:443/flask-ci-cd-demo:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-docker  # Запускать только после успешной сборки и публикации образа

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 158.160.31.148 >> ~/.ssh/known_hosts

      - name: Pull Docker image on target machine
        run: |
          ssh -i ~/.ssh/id_rsa anton@158.160.31.148 "docker pull 158.160.12.251:443/flask-ci-cd-demo:latest"

      - name: Deploy Docker image on target machine
        run: |
          ssh -i ~/.ssh/id_rsa anton@158.160.31.148 "docker stop flask-ci-cd-demo || true"
          ssh -i ~/.ssh/id_rsa anton@158.160.31.148 "docker rm flask-ci-cd-demo || true"
          ssh -i ~/.ssh/id_rsa anton@158.160.31.148 "docker run -d -p 5000:5000 --name flask-ci-cd-demo 158.160.12.251:443/flask-ci-cd-demo:latest"
