# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: test  # Запускать только после успешного выполнения тестов

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add custom DNS entry
        run: |
          echo "172.18.247.247 dock01" | sudo tee -a /etc/hosts




      - name: Build and push Docker image
        run: |
          docker build -t dock01:443/flask-ci-cd-demo:latest .
          docker push dock01:443/flask-ci-cd-demo:latest
